#ifndef MK1MF_BUILD
    /* auto-generated by util/mkbuildinf.pl for crypto/cversion.c */
    #define CFLAGS cflags
    /*
     * Generate CFLAGS as an array of individual characters. This is a
     * workaround for the situation where CFLAGS gets too long for a C90 string
     * literal
     */
    static const char cflags[] = {
        'c','o','m','p','i','l','e','r',':',' ','g','c','c',' ','-','I','.',' ',
        '-','I','.','.',' ','-','I','.','.','/','i','n','c','l','u','d','e',' ',
        ' ','-','D','D','S','O','_','D','L','F','C','N',' ','-','D','H','A','V',
        'E','_','D','L','F','C','N','_','H',' ','-','g',' ','-','W','a',',','-',
        '-','n','o','e','x','e','c','s','t','a','c','k',' ','-','O','3',' ','-',
        'f','o','m','i','t','-','f','r','a','m','e','-','p','o','i','n','t','e',
        'r',' ','-','W','a','l','l','\0'
    };
    #define PLATFORM "platform: linux-generic32"
    #define DATE "built on: Tue Nov  8 16:08:08 2022"
#endif
